### PR TITLE
GitHub workflow 

### PR DESCRIPTION
**Pull request by gkellogg**
to update rdfa variations for prefixes and terms and to update  context.jsonld.

This builds rdfa-1.1.ttl, rdfa-1.1.rdf, and rdfa-1.1.jsonld from rdfa-1.1.jsonld from rdfa-1.1.html. It also builds context.jsonld from rdfa-1.1.jsonld.

### CODE REVIEW

**Comment by gkellogg** [comment]
Once this is merged to master, which will do nothing to the context file in and of itself, it should cause an other PRs to cause the defendant files (.ttl, .rdf, .json.d, and context.jsonld) to be built and added to the PR automatically.

**Comment by iherman** [comment]
> Once this is merged to master, which will do nothing to the context file in and of itself, it should cause an other PRs to cause the defendant files (.ttl, .rdf, .json.d, and context.jsonld) to be built and added to the PR automatically.

Just for my understanding: if we merge this (I guess we should do that after merging #9) I have to prepare a separate PR bringing the html file over and, at the time of the PR, the other files will be generated? That sounds good to me.

Also, I just wonder... would it make sense to generate a 'false' Turtle context file, ie, a Turtle file just listing those `@prefix` statements? Turtle user could use this as some sort of template... WDYT?

Huge thanks!

**Comment by gkellogg** [comment]
I added the current html file (with some minor fixes) to PR #9. If we merge this first, we should be able to get #9 to be updated by the workflow.

**Comment by gkellogg** [comment]
> Also, I just wonder... would it make sense to generate a 'false' Turtle context file, ie, a Turtle file just listing those `@prefix` statements? Turtle user could use this as some sort of template... WDYT?

We could easily do that, but the only way for people to make use of it would be copy and paste.

**Comment by iherman** [comment]
> We could easily do that, but the only way for people to make use of it would be copy and paste.

Of course. It may still be useful...

**Pull request merged**
